### PR TITLE
remove order's network

### LINKED ISSUE #401: remove network for order config in the yaml structure

### PR DESCRIPTION
**Pull request by rouzwelt**
resolves #401

### CODE REVIEW

**Review by thedavidmeister — CHANGES_REQUESTED** [review]
i think this needs a corresponding update in the specs repo first

**Comment by mattyg** [comment]
To me it feels less noisy / redundant to *only* set the network for the order, and then *not* have to set it for the deployer, input tokens and output tokens. I assume the they all have to be the same network, right?

**Comment by rouzwelt** [comment]
> i think this needs a corresponding update in the specs repo first

I already made a comment on your Pr in specs repo

**Review by thedavidmeister — CHANGES_REQUESTED** [review]
lets base this off the deployer's network rather than an arbitrary token

**Pull request merged**
