### PR TITLE
chart subtitle font size

### LINKED ISSUE #656: Make subtitle font size on charts smaller than the title
## Motivation

At the moment our titles and subtitles for charts are the same size. This doesn't look that great.

Image

## Solution

Make the subtitles a smaller font size.

### PR DESCRIPTION
**Pull request by rouzwelt**
## Motivation
resolves #656 

## Solution
set html tag for chart plot subtitle with adjustable style tags and set the chart subtitle font size to small
Screenshot 2024-06-17 at 3 24 04 AM

## Checks

By submitting this for review, I'm confirming I've done the following:
- [x] made this PR as small as possible
- [x] unit-tested any new functionality
- [x] linked any relevant issues or PRs

### CODE REVIEW

**Review by hardyjosh — CHANGES_REQUESTED** [review]
This PR needs a test

**Comment by hardyjosh** [comment]
@rouzwelt also, do we need an extra js package for this, isn't it just a simple CSS fix?

```svelte
<!-- ObservableChart.svelte -->

{#if error}
  <div class="w-full border p-4 text-red-500">{error}</div>
{:else}
  <div bind:this={div} role="img" class="plot-class w-full border p-4"></div>
{/if}

<style lang="postcss">
  .plot-class :global(h2) {
    @apply text-lg font-semibold;
  }

  .plot-class :global(h3) {
    @apply text-sm;
  }
</style>
```

**Comment by rouzwelt** [comment]
> This PR needs a test

added some tests, but no sure if that satisfies what you wanted, so let me know if you need things to be added to it

**Comment by rouzwelt** [comment]
> @rouzwelt also, do we need an extra js package for this, isn't it just a simple CSS fix?
> 
> ```svelte
> 
> 
> {#if error}
>   <div class="w-full border p-4 text-red-500">{error}</div>
> {:else}
>   <div bind:this={div} role="img" class="plot-class w-full border p-4"></div>
> {/if}
> 
> <style lang="postcss">
>   .plot-class :global(h2) {
>     @apply text-lg font-semibold;
>   }
> 
>   .plot-class :global(h3) {
>     @apply text-sm;
>   }
> </style>
> ```

found an easier way and native tailwind to apply the configuration of the h2/h3 inner tags

**Review by hardyjosh — APPROVED** [review]

**Pull request merged**
